### ISSUE TITLE
jacrev(jacrev(f)) fails for matmul

### ISSUE THREAD

**Issue by Chillee** [zou3519/functorch#1]
```
from functorch import jacrev
N = 5
M = 3
W = torch.randn(N, M)
def f(x):
    return W @ x
inps = (torch.randn(M),)
print(jacrev(jacrev(f))(*inps))
```
```
Traceback (most recent call last):
  File "python_key.py", line 70, in <module>
    print(jacrev(jacrev(f))(*inps))
  File "/opt/anaconda/lib/python3.7/site-packages/functorch-0.0.1a0+e27e16f-py3.7-linux-x86_64.egg/functorch/_src/eager_transforms.py", line 87, in wrapper_fn
    result, = vmap(vjp_fn)(basis)
  File "/opt/anaconda/lib/python3.7/site-packages/functorch-0.0.1a0+e27e16f-py3.7-linux-x86_64.egg/functorch/_src/vmap.py", line 258, in wrapped
    batched_outputs = func(*batched_inputs)
  File "/opt/anaconda/lib/python3.7/site-packages/functorch-0.0.1a0+e27e16f-py3.7-linux-x86_64.egg/functorch/_src/eager_transforms.py", line 72, in wrapper
    retain_graph=retain_graph, create_graph=create_graph)
  File "/home/chilli/fb/pytorch/torch/autograd/__init__.py", line 228, in grad
    inputs, allow_unused, accumulate_grad=False)
RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn
```

**Comment by zou3519** [comment]
Hmm, I guess this should return a Tensor full of zeros. There's nothing wrong with the mechanism, it's just that we need to pass `allow_unused` to autograd and if it returns us "None" as the result (which it will) we need to turn that into a tensor full of zeros.

**Comment by zou3519** [comment]
> Hmm, I guess this should return a Tensor full of zeros. There's nothing wrong with the layering mechanism, it's just that we need to pass `allow_unused` to autograd and if it returns us "None" as the result (which it will) we need to turn that into a tensor full of zeros.

**Comment by zou3519** [comment]
There are two things that are wrong:
1. We need to pass allow_unused to autograd.grad
2. If the outputs are not part of *any* computation graph, then autograd complains even if allow_unused is True. This is the same for the grad transform, even after #5 goes in:

```
import torch
from functorch import grad
x = torch.tensor(1.)
y = torch.tensor(2.)

def unrelated(x):
    return y

# Error!
grad(unrelated)(x)
```
Will try to fix if I have time later
